### PR TITLE
Added SonarQube and Spotless configurations to pom.xml

### PR DESCRIPTION
**Pull request by Hilbrand**
Added github workflow and applied spotless.

### CODE REVIEW

**Review by BertScholten — APPROVED** [review]
LGTM

guess we'll find out if it works after it's merged?

**Comment by SerhatG** [comment]
I want to double check some stuff at Sonarcloud's side.. I'll merge after.

**Review by SerhatG — APPROVED** [review]

**Comment by SerhatG** [comment]
The Sonarcloud project was called `emission-service` instead of `aerius_emission-service`. I've updated it to match the one in this PR.

**Comment by SerhatG** [comment]
Here goes nothing..

**Pull request merged**
